export const TEAMS = [
  { group: 'A', name: 'Mexiko',              flag: '🇲🇽', wk: 99,  ref: 14.5 },
  { group: 'A', name: 'Südkorea',            flag: '🇰🇷', wk: 91,  ref: 10.5 },
  { group: 'A', name: 'Tschechien',          flag: '🇨🇿', wk: 62,  ref: 7.0  },
  { group: 'A', name: 'Südafrika',           flag: '🇿🇦', wk: 14,  ref: 1.5  },
  { group: 'B', name: 'Schweiz',             flag: '🇨🇭', wk: 99,  ref: 13.5 },
  { group: 'B', name: 'Kanada',              flag: '🇨🇦', wk: 98,  ref: 12.5 },
  { group: 'B', name: 'Bosnien-Herzegowina', flag: '🇧🇦', wk: 50,  ref: 5.5  },
  { group: 'B', name: 'Katar',              flag: '🇶🇦', wk: 20,  ref: 2.0  },
  { group: 'C', name: 'Brasilien',           flag: '🇧🇷', wk: 100, ref: 39.0 },
  { group: 'C', name: 'Marokko',             flag: '🇲🇦', wk: 99,  ref: 17.0 },
  { group: 'C', name: 'Schottland',          flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', wk: 55,  ref: 6.0  },
  { group: 'C', name: 'Haiti',               flag: '🇭🇹', wk: 13,  ref: 1.5  },
  { group: 'D', name: 'USA',                 flag: '🇺🇸', wk: 94,  ref: 14.0 },
  { group: 'D', name: 'Türkei',              flag: '🇹🇷', wk: 91,  ref: 12.5 },
  { group: 'D', name: 'Australien',          flag: '🇦🇺', wk: 69,  ref: 9.0  },
  { group: 'D', name: 'Paraguay',            flag: '🇵🇾', wk: 13,  ref: 2.0  },
  { group: 'E', name: 'Deutschland',         flag: '🇩🇪', wk: 100, ref: 29.0 },
  { group: 'E', name: 'Ecuador',             flag: '🇪🇨', wk: 93,  ref: 12.0 },
  { group: 'E', name: 'Elfenbeinküste',      flag: '🇨🇮', wk: 71,  ref: 8.0  },
  { group: 'E', name: 'Curaçao',             flag: '🇨🇼', wk: 3,   ref: 0.5  },
  { group: 'F', name: 'Niederlande',         flag: '🇳🇱', wk: 98,  ref: 23.0 },
  { group: 'F', name: 'Japan',               flag: '🇯🇵', wk: 92,  ref: 15.0 },
  { group: 'F', name: 'Schweden',            flag: '🇸🇪', wk: 54,  ref: 7.5  },
  { group: 'F', name: 'Tunesien',            flag: '🇹🇳', wk: 23,  ref: 3.5  },
  { group: 'G', name: 'Belgien',             flag: '🇧🇪', wk: 100, ref: 21.5 },
  { group: 'G', name: 'Iran',                flag: '🇮🇷', wk: 81,  ref: 8.5  },
  { group: 'G', name: 'Ägypten',             flag: '🇪🇬', wk: 76,  ref: 8.0  },
  { group: 'G', name: 'Neuseeland',          flag: '🇳🇿', wk: 10,  ref: 1.0  },
  { group: 'H', name: 'Spanien',             flag: '🇪🇸', wk: 100, ref: 49.0 },
  { group: 'H', name: 'Uruguay',             flag: '🇺🇾', wk: 99,  ref: 18.0 },
  { group: 'H', name: 'Saudi-Arabien',       flag: '🇸🇦', wk: 46,  ref: 4.5  },
  { group: 'H', name: 'Kap Verde',           flag: '🇨🇻', wk: 22,  ref: 2.5  },
  { group: 'I', name: 'Frankreich',          flag: '🇫🇷', wk: 100, ref: 48.5 },
  { group: 'I', name: 'Senegal',             flag: '🇸🇳', wk: 87,  ref: 11.5 },
  { group: 'I', name: 'Norwegen',            flag: '🇳🇴', wk: 76,  ref: 9.5  },
  { group: 'I', name: 'Irak',                flag: '🇮🇶', wk: 4,   ref: 0.5  },
  { group: 'J', name: 'Argentinien',         flag: '🇦🇷', wk: 100, ref: 36.5 },
  { group: 'J', name: 'Österreich',          flag: '🇦🇹', wk: 96,  ref: 15.5 },
  { group: 'J', name: 'Algerien',            flag: '🇩🇿', wk: 65,  ref: 7.5  },
  { group: 'J', name: 'Jordanien',           flag: '🇯🇴', wk: 5,   ref: 0.5  },
  { group: 'K', name: 'Portugal',            flag: '🇵🇹', wk: 100, ref: 33.0 },
  { group: 'K', name: 'Kolumbien',           flag: '🇨🇴', wk: 99,  ref: 17.0 },
  { group: 'K', name: 'Usbekistan',          flag: '🇺🇿', wk: 40,  ref: 4.0  },
  { group: 'K', name: 'DR Kongo',            flag: '🇨🇩', wk: 28,  ref: 3.0  },
  { group: 'L', name: 'England',             flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', wk: 100, ref: 43.0 },
  { group: 'L', name: 'Kroatien',            flag: '🇭🇷', wk: 92,  ref: 13.0 },
  { group: 'L', name: 'Ghana',               flag: '🇬🇭', wk: 63,  ref: 7.5  },
  { group: 'L', name: 'Panama',              flag: '🇵🇦', wk: 12,  ref: 1.5  },
] as const

export type Team = (typeof TEAMS)[number]
export type TeamName = Team['name']

export function getTeam(name: string): Team | undefined {
  return TEAMS.find(t => t.name === name)
}
